// Code generated by Prismic. DO NOT EDIT.

import type * as prismic from "@prismicio/client"

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		| prismic.AnyRegularField
		| prismic.GroupField
		| prismic.NestedGroupField
		| prismic.SliceZone
	>,
	TLang extends string,
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
			TSubRelationship["customtypes"],
			TLang
		>
	} & {
		// Group
		[TGroup in Extract<
			TRelationship["fields"][number],
			| prismic.CustomTypeModelFetchGroupLevel1
			| prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]: TData[TGroup["id"]] extends (
			prismic.GroupField<infer TGroupData>
		) ?
			prismic.GroupField<
				PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
			>
		:	never
	} & {
		// Other fields
		[TFieldKey in Extract<
			TRelationship["fields"][number],
			string
		>]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
	}

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string,
> = {
	[ID in Exclude<
		TCustomType[number],
		string
	>["id"]]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
			TLang
		>
	>
}[Exclude<TCustomType[number], string>["id"]]

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Logo field in *Footer*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>

	/**
	 * Brand Name field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.brand_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	brand_name: prismic.KeyTextField

	/**
	 * Navigation field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.navigation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	navigation: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<FooterDocumentData>,
		"footer",
		Lang
	>

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
	/**
	 * Logo field in *Header*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>

	/**
	 * Brand Name field in *Header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.brand_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	brand_name: prismic.KeyTextField

	/**
	 * Navigation field in *Header*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.navigation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	navigation: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>

	/**
	 * CTA field in *Header*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.cta
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<HeaderDocumentData>,
		"header",
		Lang
	>

type LandingPageDocumentDataSlicesSlice =
	| TestimonialsSlice
	| LogoCloudSlice
	| FaqSlice
	| FeatureGridSlice
	| HeroSlice

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
	/**
	 * Slices field in *Landing Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<LandingPageDocumentData>,
		"landing_page",
		Lang
	>

export type AllDocumentTypes =
	| FooterDocument
	| HeaderDocument
	| LandingPageDocument

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
	/**
	 * Heading field in *Faq → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
	/**
	 * Question field in *Faq → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField

	/**
	 * Answer field in *Faq → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.items[].answer
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	answer: prismic.KeyTextField
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<FaqSliceDefaultPrimary>,
	Simplify<FaqSliceDefaultItem>
>

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Frequently asked questions with expandable answers.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>

/**
 * Primary content in *FeatureGrid → Default → Primary*
 */
export interface FeatureGridSliceDefaultPrimary {
	/**
	 * Kicker field in *FeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Why us
	 * - **API ID Path**: feature_grid.default.primary.kicker
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	kicker: prismic.KeyTextField

	/**
	 * Title field in *FeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Intro field in *FeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.default.primary.intro
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	intro: prismic.KeyTextField
}

/**
 * Primary content in *FeatureGrid → Items*
 */
export interface FeatureGridSliceDefaultItem {
	/**
	 * Feature image field in *FeatureGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.items[].feature_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	feature_image: prismic.ImageField<never>

	/**
	 * Feature title field in *FeatureGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.items[].feature_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	feature_title: prismic.KeyTextField

	/**
	 * Feature body field in *FeatureGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.items[].feature_body
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	feature_body: prismic.KeyTextField
}

/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<FeatureGridSliceDefaultPrimary>,
	Simplify<FeatureGridSliceDefaultItem>
>

/**
 * Slice variation for *FeatureGrid*
 */
type FeatureGridSliceVariation = FeatureGridSliceDefault

/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: Section heading with a grid of feature tiles.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridSlice = prismic.SharedSlice<
	"feature_grid",
	FeatureGridSliceVariation
>

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Eyebrow field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Short label above the headline
	 * - **API ID Path**: hero.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField

	/**
	 * Headline field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField

	/**
	 * Description field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField

	/**
	 * Primary CTA label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField

	/**
	 * Secondary CTA label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.secondary_cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	secondary_cta_label: prismic.KeyTextField

	/**
	 * Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<HeroSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Headline, supporting copy, and primary or secondary calls to action.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>

/**
 * Primary content in *LogoCloud → Default → Primary*
 */
export interface LogoCloudSliceDefaultPrimary {
	/**
	 * Heading field in *LogoCloud → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Trusted by industry leaders
	 * - **API ID Path**: logo_cloud.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField
}

/**
 * Primary content in *LogoCloud → Items*
 */
export interface LogoCloudSliceDefaultItem {
	/**
	 * Logo field in *LogoCloud → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_cloud.items[].logo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>

	/**
	 * Company name field in *LogoCloud → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Used as alt text for the logo
	 * - **API ID Path**: logo_cloud.items[].company_name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	company_name: prismic.KeyTextField
}

/**
 * Default variation for LogoCloud Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoCloudSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<LogoCloudSliceDefaultPrimary>,
	Simplify<LogoCloudSliceDefaultItem>
>

/**
 * Slice variation for *LogoCloud*
 */
type LogoCloudSliceVariation = LogoCloudSliceDefault

/**
 * LogoCloud Shared Slice
 *
 * - **API ID**: `logo_cloud`
 * - **Description**: A heading with a grid of partner or client logos.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoCloudSlice = prismic.SharedSlice<
	"logo_cloud",
	LogoCloudSliceVariation
>

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
	/**
	 * Heading field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField

	/**
	 * Subheading field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subheading: prismic.KeyTextField
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
	/**
	 * Quote field in *Testimonials → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].quote
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quote: prismic.KeyTextField

	/**
	 * Author field in *Testimonials → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].author
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField

	/**
	 * Role or company field in *Testimonials → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].role
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField

	/**
	 * Avatar field in *Testimonials → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].avatar
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	avatar: prismic.ImageField<never>
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<TestimonialsSliceDefaultPrimary>,
	Simplify<TestimonialsSliceDefaultItem>
>

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Quotes from customers with optional avatars.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
	"testimonials",
	TestimonialsSliceVariation
>

declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>
	}

	namespace Content {
		export type {
			FooterDocument,
			FooterDocumentData,
			HeaderDocument,
			HeaderDocumentData,
			LandingPageDocument,
			LandingPageDocumentData,
			LandingPageDocumentDataSlicesSlice,
			AllDocumentTypes,
			FaqSlice,
			FaqSliceDefaultPrimary,
			FaqSliceDefaultItem,
			FaqSliceVariation,
			FaqSliceDefault,
			FeatureGridSlice,
			FeatureGridSliceDefaultPrimary,
			FeatureGridSliceDefaultItem,
			FeatureGridSliceVariation,
			FeatureGridSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			LogoCloudSlice,
			LogoCloudSliceDefaultPrimary,
			LogoCloudSliceDefaultItem,
			LogoCloudSliceVariation,
			LogoCloudSliceDefault,
			TestimonialsSlice,
			TestimonialsSliceDefaultPrimary,
			TestimonialsSliceDefaultItem,
			TestimonialsSliceVariation,
			TestimonialsSliceDefault,
		}
	}
}
