// Code generated by Prismic. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
	faq: dynamic(() => import("./Faq")),
	feature_grid: dynamic(() => import("./FeatureGrid")),
	hero: dynamic(() => import("./Hero")),
	logo_cloud: dynamic(() => import("./LogoCloud")),
	testimonials: dynamic(() => import("./Testimonials")),
}
